### ISSUE TITLE
The searched performance under this proxy data setting only achieve 95.869998

### ISSUE THREAD

**Issue by linhaojia13** [nabk89/NAS-with-Proxy-data#2]
Above all, thank you for your open source.
First, I executed DARTS with proxy data via running the command provided by you (“python train_search_proxy_data.py --gpu 0 --histogram --histogram_type 1”).
Then, I train the searched architecture. However, the test error after retraining is 4.13, which is far away from ~3.0 reported in the paper. 
The output log is as following:
"11/02 08:04:40 AM valid_acc 95.789998, best_acc 95.869998 (at epoch 589)"

It seems that this performance gap is too big to be attributed to the randomness of the original DARTS. Does this means the proxy data selection method proposed in your paper is inrobust？ Have you observed such low search performance in your experiments?

**Comment by nabk89** [comment]
Thank you for your interest in our research.
In the previous experiments we had, we conducted the search process with three different seeds,
and we did not encounter results with such large performance gap like your search result.
Does the search result include many skip connection?
I'm also curious about what causes the performance drop in your result.

I'll perform the search process using this code with the default seed and share the result ASAP (not now, because I'm busily preparing other works for conferences).

**Comment by linhaojia13** [comment]
Thank you for your reply! @nabk89 
The searched result does not include many skip connection, which is as following:

my_do = Genotype(normal=[('dil_conv_3x3', 0), ('sep_conv_3x3', 1), ('dil_conv_5x5', 2), ('sep_conv_5x5', 1), ('dil_conv_3x3', 1), ('sep_conv_3x3', 0), ('dil_conv_5x5', 4), ('dil_conv_5x5', 2)], normal_concat=range(2, 6), reduce=[('max_pool_3x3', 0), ('sep_conv_5x5', 1), ('max_pool_3x3', 0), ('skip_connect', 2), ('max_pool_3x3', 0), ('dil_conv_3x3', 2), ('dil_conv_5x5', 4), ('dil_conv_5x5', 2)], reduce_concat=range(2, 6))

Could you please provide the seeds used in your experiments? I realy appreciate your idea of proxy data selection, and want to observe the impressive results in my own experiments.
In addition, if there are some other experiments configuration not provided in this repository, could you please inform me for my further try?

**Comment by nabk89** [comment]
I trained your searched architecture ("my_do") with cutout and auxiliary loss, as in "cifar10-eval" in script.sh.
In my case, your architecture achieves 97.05% for test accuracy.
Did you train your architecture with cutout and auxiliary loss?

**Comment by linhaojia13** [comment]
You are right. When I trained this architecture again with cutout and aux, the acc reached 97.19.
Thank you very much!
